"""Domain model: Symbol, Module, Import, CallSite, Route, HttpClientCall, Kafka*, Chunk."""

from code_spider.symbols.fqn import file_to_module_fqn, qualify
from code_spider.symbols.model import (
    CallSite,
    Chunk,
    FileRecord,
    HttpClientCall,
    HttpFlowEdge,
    Import,
    KafkaConsumer,
    KafkaFlowEdge,
    KafkaProducer,
    KafkaTopic,
    Module,
    ParseResult,
    ResolvedCall,
    Route,
    Span,
    Symbol,
    SymbolKind,
    WorkspaceParseBundle,
)

__all__ = [
    "CallSite",
    "Chunk",
    "FileRecord",
    "HttpClientCall",
    "HttpFlowEdge",
    "Import",
    "KafkaConsumer",
    "KafkaFlowEdge",
    "KafkaProducer",
    "KafkaTopic",
    "Module",
    "ParseResult",
    "ResolvedCall",
    "Route",
    "Span",
    "Symbol",
    "SymbolKind",
    "WorkspaceParseBundle",
    "file_to_module_fqn",
    "qualify",
]
